# 브로드 캐스팅

In [6]:
import numpy as np

In [7]:
a1 = np.linspace(1, 12, 12).reshape(3, 4)
a2 = np.arange(1, 5) # [1,2,3,4] , 가로 벡터
a3 = a2.reshape(4, 1) # [1,2,3,4] , 세로 벡터
a4 = a1.reshape(3,1,4) # 3차원 행렬
print(a1)
print(a2)
print(a3)
print(a4)


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[[ 1.  2.  3.  4.]]

 [[ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]]]


In [9]:
print(a1 + a2)
print((a1 + a2).shape)
print(a2+a3)
print((a2+a3).shape)
print(a1+a4)
print((a1+a4).shape)

[[ 2.  4.  6.  8.]
 [ 6.  8. 10. 12.]
 [10. 12. 14. 16.]]
(3, 4)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
(4, 4)
[[[ 2.  4.  6.  8.]
  [ 6.  8. 10. 12.]
  [10. 12. 14. 16.]]

 [[ 6.  8. 10. 12.]
  [10. 12. 14. 16.]
  [14. 16. 18. 20.]]

 [[10. 12. 14. 16.]
  [14. 16. 18. 20.]
  [18. 20. 22. 24.]]]
(3, 3, 4)


# 넘파이 인덱싱

In [13]:
a1 = np.arange(1,10+1) **2
a2 = a1[2:9]
print(a1)
print(a2)

a1[3] = a1[1] + a1[2] # 원소의 변경
a2[5:2] # 슬라이싱
a2[:5:2] = 10_000 
# for i in range(len(a1)):
#     print(a1[(i+1)*-1], end=', ')
print(a1[::-1])
print()

[  1   4   9  16  25  36  49  64  81 100]
[ 9 16 25 36 49 64 81]
100, 81, 64, 10000, 36, 10000, 13, 10000, 4, 1, 


In [ ]:
a1 = np.fromfunction(lambda i, j: (i+1) * (j+1), (9,9), dtype=int)